version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: java-app-backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    hostname: localhost
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
