CREATE TABLE transactions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID           NOT NULL UNIQUE,
    account_id    BIGINT         NOT NULL,
    amount        DECIMAL(19, 4) NOT NULL,
    type          VARCHAR(50)    NOT NULL,
    currency      VARCHAR(10)    NOT NULL,
    exchange_rate DECIMAL(19, 4) NOT NULL,
    description   VARCHAR(255),
    created_at    TIMESTAMP      NOT NULL,
    updated_at    TIMESTAMP      NOT NULL,

    CONSTRAINT fk_transactions_account
        FOREIGN KEY (account_id)
            REFERENCES accounts (id)
);